[2025-10-14 14:57:12,879] {processor.py:153} INFO - Started process (PID=13331) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:12,880] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 14:57:12,880] {logging_mixin.py:115} INFO - [2025-10-14 14:57:12,880] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:12,901] {logging_mixin.py:115} INFO - [2025-10-14 14:57:12,900] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 14:57:12,901] {logging_mixin.py:115} INFO - [2025-10-14 14:57:12,901] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 14:57:12,901] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:12,917] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-14 14:57:49,483] {processor.py:153} INFO - Started process (PID=13542) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:49,483] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 14:57:49,484] {logging_mixin.py:115} INFO - [2025-10-14 14:57:49,484] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:49,508] {logging_mixin.py:115} INFO - [2025-10-14 14:57:49,508] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 14:57:49,508] {logging_mixin.py:115} INFO - [2025-10-14 14:57:49,508] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 14:57:49,509] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:57:49,526] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-10-14 14:58:23,756] {processor.py:153} INFO - Started process (PID=13702) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:23,757] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 14:58:23,758] {logging_mixin.py:115} INFO - [2025-10-14 14:58:23,758] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:23,782] {logging_mixin.py:115} INFO - [2025-10-14 14:58:23,781] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 14:58:23,782] {logging_mixin.py:115} INFO - [2025-10-14 14:58:23,782] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 14:58:23,782] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:23,796] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-10-14 14:58:56,871] {processor.py:153} INFO - Started process (PID=13757) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:56,872] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 14:58:56,873] {logging_mixin.py:115} INFO - [2025-10-14 14:58:56,873] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:56,907] {logging_mixin.py:115} INFO - [2025-10-14 14:58:56,906] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 14:58:56,907] {logging_mixin.py:115} INFO - [2025-10-14 14:58:56,907] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 14:58:56,908] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:58:56,928] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-10-14 14:59:30,782] {processor.py:153} INFO - Started process (PID=13971) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:59:30,782] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 14:59:30,783] {logging_mixin.py:115} INFO - [2025-10-14 14:59:30,783] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:59:30,801] {logging_mixin.py:115} INFO - [2025-10-14 14:59:30,801] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 14:59:30,801] {logging_mixin.py:115} INFO - [2025-10-14 14:59:30,801] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 14:59:30,802] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 14:59:30,816] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-14 15:00:04,499] {processor.py:153} INFO - Started process (PID=14026) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:04,500] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:00:04,501] {logging_mixin.py:115} INFO - [2025-10-14 15:00:04,501] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:04,520] {logging_mixin.py:115} INFO - [2025-10-14 15:00:04,519] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:00:04,520] {logging_mixin.py:115} INFO - [2025-10-14 15:00:04,520] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:00:04,520] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:04,535] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-10-14 15:00:37,654] {processor.py:153} INFO - Started process (PID=14081) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:37,654] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:00:37,655] {logging_mixin.py:115} INFO - [2025-10-14 15:00:37,655] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:37,677] {logging_mixin.py:115} INFO - [2025-10-14 15:00:37,676] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:00:37,677] {logging_mixin.py:115} INFO - [2025-10-14 15:00:37,677] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:00:37,677] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:00:37,691] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-14 15:01:13,057] {processor.py:153} INFO - Started process (PID=14446) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:13,058] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:01:13,059] {logging_mixin.py:115} INFO - [2025-10-14 15:01:13,058] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:13,076] {logging_mixin.py:115} INFO - [2025-10-14 15:01:13,076] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:01:13,076] {logging_mixin.py:115} INFO - [2025-10-14 15:01:13,076] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:01:13,077] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:13,091] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-14 15:01:45,783] {processor.py:153} INFO - Started process (PID=14578) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:45,784] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:01:45,785] {logging_mixin.py:115} INFO - [2025-10-14 15:01:45,784] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:45,807] {logging_mixin.py:115} INFO - [2025-10-14 15:01:45,807] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:01:45,807] {logging_mixin.py:115} INFO - [2025-10-14 15:01:45,807] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:01:45,807] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:01:45,826] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-10-14 15:02:22,118] {processor.py:153} INFO - Started process (PID=14816) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:22,119] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:02:22,120] {logging_mixin.py:115} INFO - [2025-10-14 15:02:22,120] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:22,139] {logging_mixin.py:115} INFO - [2025-10-14 15:02:22,139] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:02:22,140] {logging_mixin.py:115} INFO - [2025-10-14 15:02:22,140] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:02:22,140] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:22,155] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 15:02:54,711] {processor.py:153} INFO - Started process (PID=14978) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:54,712] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:02:54,712] {logging_mixin.py:115} INFO - [2025-10-14 15:02:54,712] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:54,732] {logging_mixin.py:115} INFO - [2025-10-14 15:02:54,731] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:02:54,732] {logging_mixin.py:115} INFO - [2025-10-14 15:02:54,732] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:02:54,732] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:02:54,747] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 15:10:01,369] {processor.py:153} INFO - Started process (PID=15892) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:01,369] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:10:01,371] {logging_mixin.py:115} INFO - [2025-10-14 15:10:01,370] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:01,390] {logging_mixin.py:115} INFO - [2025-10-14 15:10:01,389] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:10:01,390] {logging_mixin.py:115} INFO - [2025-10-14 15:10:01,390] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:10:01,390] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:01,404] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-14 15:10:36,990] {processor.py:153} INFO - Started process (PID=15950) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:36,991] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:10:36,991] {logging_mixin.py:115} INFO - [2025-10-14 15:10:36,991] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:37,014] {logging_mixin.py:115} INFO - [2025-10-14 15:10:37,013] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:10:37,014] {logging_mixin.py:115} INFO - [2025-10-14 15:10:37,014] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:10:37,014] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:10:37,030] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-10-14 15:11:11,186] {processor.py:153} INFO - Started process (PID=16031) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:11,187] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:11:11,187] {logging_mixin.py:115} INFO - [2025-10-14 15:11:11,187] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:11,218] {logging_mixin.py:115} INFO - [2025-10-14 15:11:11,217] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:11:11,218] {logging_mixin.py:115} INFO - [2025-10-14 15:11:11,218] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:11:11,218] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:11,240] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2025-10-14 15:11:44,246] {processor.py:153} INFO - Started process (PID=16166) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:44,247] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:11:44,247] {logging_mixin.py:115} INFO - [2025-10-14 15:11:44,247] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:44,268] {logging_mixin.py:115} INFO - [2025-10-14 15:11:44,268] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:11:44,269] {logging_mixin.py:115} INFO - [2025-10-14 15:11:44,269] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:11:44,269] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:11:44,286] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-10-14 15:12:19,443] {processor.py:153} INFO - Started process (PID=16224) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:19,444] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:12:19,445] {logging_mixin.py:115} INFO - [2025-10-14 15:12:19,445] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:19,468] {logging_mixin.py:115} INFO - [2025-10-14 15:12:19,467] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:12:19,468] {logging_mixin.py:115} INFO - [2025-10-14 15:12:19,468] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:12:19,468] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:19,486] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-10-14 15:12:52,204] {processor.py:153} INFO - Started process (PID=16279) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:52,206] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:12:52,208] {logging_mixin.py:115} INFO - [2025-10-14 15:12:52,208] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:52,236] {logging_mixin.py:115} INFO - [2025-10-14 15:12:52,235] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:12:52,236] {logging_mixin.py:115} INFO - [2025-10-14 15:12:52,236] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:12:52,236] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:12:52,252] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-10-14 15:13:25,860] {processor.py:153} INFO - Started process (PID=16337) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:25,861] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:13:25,861] {logging_mixin.py:115} INFO - [2025-10-14 15:13:25,861] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:25,882] {logging_mixin.py:115} INFO - [2025-10-14 15:13:25,881] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:13:25,882] {logging_mixin.py:115} INFO - [2025-10-14 15:13:25,882] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:13:25,882] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:25,897] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-10-14 15:13:59,274] {processor.py:153} INFO - Started process (PID=16392) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:59,275] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:13:59,275] {logging_mixin.py:115} INFO - [2025-10-14 15:13:59,275] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:59,294] {logging_mixin.py:115} INFO - [2025-10-14 15:13:59,293] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:13:59,294] {logging_mixin.py:115} INFO - [2025-10-14 15:13:59,294] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:13:59,294] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:13:59,308] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-14 15:14:34,618] {processor.py:153} INFO - Started process (PID=16452) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:14:34,619] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:14:34,620] {logging_mixin.py:115} INFO - [2025-10-14 15:14:34,620] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:14:34,643] {logging_mixin.py:115} INFO - [2025-10-14 15:14:34,643] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:14:34,643] {logging_mixin.py:115} INFO - [2025-10-14 15:14:34,643] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:14:34,644] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:14:34,657] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-10-14 15:15:10,269] {processor.py:153} INFO - Started process (PID=16562) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:10,271] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:15:10,271] {logging_mixin.py:115} INFO - [2025-10-14 15:15:10,271] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:10,294] {logging_mixin.py:115} INFO - [2025-10-14 15:15:10,294] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:15:10,295] {logging_mixin.py:115} INFO - [2025-10-14 15:15:10,295] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:15:10,295] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:10,311] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-10-14 15:15:45,492] {processor.py:153} INFO - Started process (PID=16618) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:45,492] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:15:45,493] {logging_mixin.py:115} INFO - [2025-10-14 15:15:45,493] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:45,511] {logging_mixin.py:115} INFO - [2025-10-14 15:15:45,510] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:15:45,511] {logging_mixin.py:115} INFO - [2025-10-14 15:15:45,511] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:15:45,511] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:15:45,524] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 15:16:21,343] {processor.py:153} INFO - Started process (PID=16831) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:21,344] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:16:21,345] {logging_mixin.py:115} INFO - [2025-10-14 15:16:21,344] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:21,369] {logging_mixin.py:115} INFO - [2025-10-14 15:16:21,368] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:16:21,369] {logging_mixin.py:115} INFO - [2025-10-14 15:16:21,369] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:16:21,369] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:21,383] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-10-14 15:16:54,557] {processor.py:153} INFO - Started process (PID=17043) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:54,558] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:16:54,559] {logging_mixin.py:115} INFO - [2025-10-14 15:16:54,559] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:54,587] {logging_mixin.py:115} INFO - [2025-10-14 15:16:54,586] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:16:54,587] {logging_mixin.py:115} INFO - [2025-10-14 15:16:54,587] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:16:54,587] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:16:54,601] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-10-14 15:17:27,962] {processor.py:153} INFO - Started process (PID=17098) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:17:27,963] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:17:27,964] {logging_mixin.py:115} INFO - [2025-10-14 15:17:27,964] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:17:27,987] {logging_mixin.py:115} INFO - [2025-10-14 15:17:27,986] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:17:27,987] {logging_mixin.py:115} INFO - [2025-10-14 15:17:27,987] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:17:27,987] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:17:28,002] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-10-14 15:58:59,622] {processor.py:153} INFO - Started process (PID=19881) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:58:59,623] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:58:59,624] {logging_mixin.py:115} INFO - [2025-10-14 15:58:59,624] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:58:59,644] {logging_mixin.py:115} INFO - [2025-10-14 15:58:59,643] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:58:59,644] {logging_mixin.py:115} INFO - [2025-10-14 15:58:59,644] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:58:59,644] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:58:59,658] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-14 15:59:33,035] {processor.py:153} INFO - Started process (PID=20092) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:59:33,036] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 15:59:33,036] {logging_mixin.py:115} INFO - [2025-10-14 15:59:33,036] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:59:33,055] {logging_mixin.py:115} INFO - [2025-10-14 15:59:33,055] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 15:59:33,055] {logging_mixin.py:115} INFO - [2025-10-14 15:59:33,055] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 15:59:33,056] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 15:59:33,069] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-14 16:00:05,642] {processor.py:153} INFO - Started process (PID=20147) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:05,643] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:00:05,644] {logging_mixin.py:115} INFO - [2025-10-14 16:00:05,643] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:05,667] {logging_mixin.py:115} INFO - [2025-10-14 16:00:05,666] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:00:05,667] {logging_mixin.py:115} INFO - [2025-10-14 16:00:05,667] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:00:05,667] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:05,680] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-10-14 16:00:38,289] {processor.py:153} INFO - Started process (PID=20205) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:38,290] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:00:38,290] {logging_mixin.py:115} INFO - [2025-10-14 16:00:38,290] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:38,311] {logging_mixin.py:115} INFO - [2025-10-14 16:00:38,310] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:00:38,311] {logging_mixin.py:115} INFO - [2025-10-14 16:00:38,311] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:00:38,311] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:00:38,325] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 16:01:11,456] {processor.py:153} INFO - Started process (PID=20260) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:11,457] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:01:11,457] {logging_mixin.py:115} INFO - [2025-10-14 16:01:11,457] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:11,477] {logging_mixin.py:115} INFO - [2025-10-14 16:01:11,476] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:01:11,477] {logging_mixin.py:115} INFO - [2025-10-14 16:01:11,477] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:01:11,477] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:11,492] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 16:01:47,244] {processor.py:153} INFO - Started process (PID=20318) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:47,245] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:01:47,245] {logging_mixin.py:115} INFO - [2025-10-14 16:01:47,245] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:47,262] {logging_mixin.py:115} INFO - [2025-10-14 16:01:47,262] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:01:47,263] {logging_mixin.py:115} INFO - [2025-10-14 16:01:47,263] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:01:47,263] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:01:47,276] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-10-14 16:02:21,945] {processor.py:153} INFO - Started process (PID=20377) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:21,946] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:02:21,947] {logging_mixin.py:115} INFO - [2025-10-14 16:02:21,946] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:21,965] {logging_mixin.py:115} INFO - [2025-10-14 16:02:21,964] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:02:21,965] {logging_mixin.py:115} INFO - [2025-10-14 16:02:21,965] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:02:21,965] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:21,978] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-14 16:02:55,157] {processor.py:153} INFO - Started process (PID=20432) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:55,157] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:02:55,158] {logging_mixin.py:115} INFO - [2025-10-14 16:02:55,158] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:55,176] {logging_mixin.py:115} INFO - [2025-10-14 16:02:55,176] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:02:55,177] {logging_mixin.py:115} INFO - [2025-10-14 16:02:55,177] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:02:55,177] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:02:55,191] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-10-14 16:03:28,724] {processor.py:153} INFO - Started process (PID=20490) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:03:28,724] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:03:28,725] {logging_mixin.py:115} INFO - [2025-10-14 16:03:28,725] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:03:28,745] {logging_mixin.py:115} INFO - [2025-10-14 16:03:28,743] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:03:28,745] {logging_mixin.py:115} INFO - [2025-10-14 16:03:28,745] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:03:28,745] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:03:28,759] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-10-14 16:04:02,292] {processor.py:153} INFO - Started process (PID=20596) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:02,292] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:04:02,293] {logging_mixin.py:115} INFO - [2025-10-14 16:04:02,293] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:02,310] {logging_mixin.py:115} INFO - [2025-10-14 16:04:02,310] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:04:02,311] {logging_mixin.py:115} INFO - [2025-10-14 16:04:02,311] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:04:02,311] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:02,324] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-10-14 16:04:35,582] {processor.py:153} INFO - Started process (PID=20654) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:35,583] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:04:35,584] {logging_mixin.py:115} INFO - [2025-10-14 16:04:35,584] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:35,607] {logging_mixin.py:115} INFO - [2025-10-14 16:04:35,606] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:04:35,607] {logging_mixin.py:115} INFO - [2025-10-14 16:04:35,607] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:04:35,607] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:04:35,620] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-10-14 16:05:10,564] {processor.py:153} INFO - Started process (PID=20714) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:10,565] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:05:10,566] {logging_mixin.py:115} INFO - [2025-10-14 16:05:10,566] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:10,592] {logging_mixin.py:115} INFO - [2025-10-14 16:05:10,592] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:05:10,592] {logging_mixin.py:115} INFO - [2025-10-14 16:05:10,592] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:05:10,592] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:10,609] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-10-14 16:05:45,589] {processor.py:153} INFO - Started process (PID=20774) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:45,590] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:05:45,591] {logging_mixin.py:115} INFO - [2025-10-14 16:05:45,591] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:45,615] {logging_mixin.py:115} INFO - [2025-10-14 16:05:45,615] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:05:45,616] {logging_mixin.py:115} INFO - [2025-10-14 16:05:45,616] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:05:45,616] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:05:45,634] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-10-14 16:06:19,034] {processor.py:153} INFO - Started process (PID=20829) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:19,035] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:06:19,036] {logging_mixin.py:115} INFO - [2025-10-14 16:06:19,035] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:19,062] {logging_mixin.py:115} INFO - [2025-10-14 16:06:19,061] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:06:19,062] {logging_mixin.py:115} INFO - [2025-10-14 16:06:19,062] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:06:19,062] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:19,077] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-10-14 16:06:55,959] {processor.py:153} INFO - Started process (PID=20889) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:55,961] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:06:55,962] {logging_mixin.py:115} INFO - [2025-10-14 16:06:55,962] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:55,981] {logging_mixin.py:115} INFO - [2025-10-14 16:06:55,981] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:06:55,981] {logging_mixin.py:115} INFO - [2025-10-14 16:06:55,981] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:06:55,982] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:06:55,998] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-10-14 16:07:30,094] {processor.py:153} INFO - Started process (PID=21051) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:07:30,095] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:07:30,096] {logging_mixin.py:115} INFO - [2025-10-14 16:07:30,095] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:07:30,126] {logging_mixin.py:115} INFO - [2025-10-14 16:07:30,126] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:07:30,127] {logging_mixin.py:115} INFO - [2025-10-14 16:07:30,126] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:07:30,127] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:07:30,150] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-10-14 16:08:02,407] {processor.py:153} INFO - Started process (PID=21362) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:02,409] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:08:02,411] {logging_mixin.py:115} INFO - [2025-10-14 16:08:02,411] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:02,445] {logging_mixin.py:115} INFO - [2025-10-14 16:08:02,444] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:08:02,445] {logging_mixin.py:115} INFO - [2025-10-14 16:08:02,445] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:08:02,445] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:02,459] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-10-14 16:08:38,999] {processor.py:153} INFO - Started process (PID=21549) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:39,000] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:08:39,001] {logging_mixin.py:115} INFO - [2025-10-14 16:08:39,001] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:39,025] {logging_mixin.py:115} INFO - [2025-10-14 16:08:39,024] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:08:39,025] {logging_mixin.py:115} INFO - [2025-10-14 16:08:39,025] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:08:39,025] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:08:39,039] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-10-14 16:25:34,413] {processor.py:153} INFO - Started process (PID=22779) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:25:34,413] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:25:34,414] {logging_mixin.py:115} INFO - [2025-10-14 16:25:34,414] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:25:34,437] {logging_mixin.py:115} INFO - [2025-10-14 16:25:34,436] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:25:34,437] {logging_mixin.py:115} INFO - [2025-10-14 16:25:34,437] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:25:34,437] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:25:34,452] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-10-14 16:26:09,322] {processor.py:153} INFO - Started process (PID=22888) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:09,323] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:26:09,324] {logging_mixin.py:115} INFO - [2025-10-14 16:26:09,324] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:09,350] {logging_mixin.py:115} INFO - [2025-10-14 16:26:09,349] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:26:09,350] {logging_mixin.py:115} INFO - [2025-10-14 16:26:09,350] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:26:09,350] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:09,363] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-10-14 16:26:43,197] {processor.py:153} INFO - Started process (PID=22946) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:43,197] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:26:43,198] {logging_mixin.py:115} INFO - [2025-10-14 16:26:43,198] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:43,216] {logging_mixin.py:115} INFO - [2025-10-14 16:26:43,215] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:26:43,216] {logging_mixin.py:115} INFO - [2025-10-14 16:26:43,216] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:26:43,216] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:26:43,229] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-10-14 16:27:16,181] {processor.py:153} INFO - Started process (PID=23001) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:16,182] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:27:16,182] {logging_mixin.py:115} INFO - [2025-10-14 16:27:16,182] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:16,202] {logging_mixin.py:115} INFO - [2025-10-14 16:27:16,201] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:27:16,202] {logging_mixin.py:115} INFO - [2025-10-14 16:27:16,202] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:27:16,202] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:16,215] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-10-14 16:27:51,546] {processor.py:153} INFO - Started process (PID=23162) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:51,547] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:27:51,547] {logging_mixin.py:115} INFO - [2025-10-14 16:27:51,547] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:51,565] {logging_mixin.py:115} INFO - [2025-10-14 16:27:51,565] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:27:51,565] {logging_mixin.py:115} INFO - [2025-10-14 16:27:51,565] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:27:51,565] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:27:51,579] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-10-14 16:28:25,224] {processor.py:153} INFO - Started process (PID=23323) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:28:25,225] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:28:25,225] {logging_mixin.py:115} INFO - [2025-10-14 16:28:25,225] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:28:25,245] {logging_mixin.py:115} INFO - [2025-10-14 16:28:25,245] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:28:25,246] {logging_mixin.py:115} INFO - [2025-10-14 16:28:25,245] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:28:25,246] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:28:25,260] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-10-14 16:28:59,985] {processor.py:153} INFO - Started process (PID=23381) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:28:59,986] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:28:59,987] {logging_mixin.py:115} INFO - [2025-10-14 16:28:59,987] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:29:00,005] {logging_mixin.py:115} INFO - [2025-10-14 16:29:00,005] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:29:00,005] {logging_mixin.py:115} INFO - [2025-10-14 16:29:00,005] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:29:00,005] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:29:00,022] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-10-14 16:29:32,342] {processor.py:153} INFO - Started process (PID=23594) to work on /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:29:32,343] {processor.py:641} INFO - Processing file /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-10-14 16:29:32,343] {logging_mixin.py:115} INFO - [2025-10-14 16:29:32,343] {dagbag.py:507} INFO - Filling up the DagBag from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:29:32,363] {logging_mixin.py:115} INFO - [2025-10-14 16:29:32,361] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-10-14 16:29:32,363] {logging_mixin.py:115} INFO - [2025-10-14 16:29:32,363] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-10-14 16:29:32,363] {processor.py:653} WARNING - No viable dags retrieved from /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-10-14 16:29:32,378] {processor.py:161} INFO - Processing /root/Projects/etlX/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
